重构cicd脚本

diff --git a/.script/pre-push b/.script/pre-push
--- a/.script/pre-push
+++ b/.script/pre-push
@@ -24,18 +24,8 @@ remote=$1
 url=$2
 echo >&2 "Try pushing $2 to $1"
 
-TEST="make e2e"
+TEST="make test"
 LINTER="make lint"
-
-# Run test and return if failed
-printf "Running go test..."
-$TEST
-RESULT=$?
-if [ $RESULT -ne 0 ]; then
-  echo >&2 "$TEST"
-  echo >&2 "Check code to pass test."
-  exit 1
-fi
 
 # Run linter and return if failed
 printf "Running go linter..."
@@ -44,6 +34,16 @@ RESULT=$?
 if [ $RESULT -ne 0 ]; then
   echo >&2 "$LINTER"
   echo >&2 "Check code to pass linter."
+  exit 1
+fi
+
+# Run test and return if failed
+printf "Running go test..."
+$TEST
+RESULT=$?
+if [ $RESULT -ne 0 ]; then
+  echo >&2 "$TEST"
+  echo >&2 "Check code to pass test."
   exit 1
 fi
 
